version: '3'
services:
  web:
    image: nginx:1.15.6
    ports:
      - "8000:80"
    depends_on: # 追加
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    volumes:
     - .:/var/www/html
    depends_on:
      - mysql
  
  # mysql-data:
  #   image: miatto88/my_sql_data_demo
  #   volumes:
  #     - var/lib/mysql
    
  mysql:
    platform: linux/x86_64 # m1 apple silicon 用の記述
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: common
      MYSQL_USER: miatto
      MYSQL_PASSWORD: miatto
      MYSQL_ROOT_PASSWORD: miatto
    ports:
      - "3306:3306"
    volumes:
      -  ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=miatto
    links:
      - mysql
    ports:
      - 8010:80
    volumes:
      - "./phpmyadmin/sessions:/sessions"

volumes:
  mysql-data:
